name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue:

  gatt_service_numbers:
    version: "^0.1.0"
    #git:
    #  url: git://github.com/winksaville/gatt_service_numbers_x.git
    path: ../gatt_service_numbers

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
